# .github/workflows/app.yml

name: Product Availability Checker

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [check-availability]
  workflow_dispatch:
    inputs:
      force_notify:
        description: "Force notification regardless of previous state"
        required: false
        type: boolean
        default: false
      DEBUG_ENABLED:
        type: boolean
        description: "Run the build with tmate debugging enabled."
        required: false
        default: false

jobs:
  check-product:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Cache Chrome and ChromeDriver
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/selenium
            /usr/bin/google-chrome*
            /usr/bin/chromedriver*
          key: chrome-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: pip install -r requirements.txt --disable-pip-version-check

      - name: Create .env file
        run: |
          echo "${{ secrets.ENVS }}" > .env
          if [ "${{ github.event.inputs.force_notify }}" = "true" ]; then
            echo "FORCE_NOTIFY=true" >> .env
          fi

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@master
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.DEBUG_ENABLED }}
        with:
          detached: true

      - name: Run script
        run: python main.py
        env:
          # Optimize Chrome for CI
          CHROME_NO_SANDBOX: "true"
          CHROME_DISABLE_GPU: "true"
